#!/usr/bin/env bash
set -euo pipefail

echo "== Comentarios/prints/IA sospechosos =="
grep -IRn --exclude-dir=.git --exclude-dir=build --exclude=*.apk \
  -E 'TODO|FIXME|HACK|println\(|Log\.d\(|System\.out\.println|Generated by|ChatGPT|Copilot|Claude|Gemini|GPT' . || true

echo
echo "== Dependencias legacy support =="
grep -IRn --exclude-dir=.git --exclude-dir=build -E 'com\.android\.support\.' . || true

echo
echo "== Binarios/llaves fuera de lugar =="
find . -type f \( -name "*.apk" -o -name "*.aab" -o -name "*.keystore" -o -name "*.jks" -o -name "*.so" \) -print | sed 's/^/BIN: /' || true
